[theme]
# Apple-inspired minimal theme
primaryColor = "#007AFF"                # iOS blue accent
backgroundColor = "#FFFFFF"              # Pure white background
secondaryBackgroundColor = "#F5F5F7"     # Subtle Apple gray
textColor = "#1D1D1F"                    # Near-black text
font = "sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
